# Use a base image with Java 11
FROM gayatri589/open-jdk 
  
WORKDIR /app

ARG imageName=directory-service
ENV IMAGE_NAME=${imageName}

COPY target/${IMAGE_NAME}.jar ${IMAGE_NAME}.jar

ENTRYPOINT ["sh", "-c", "java -jar /app/${IMAGE_NAME}.jar"]
