# Use a base image with Java 11
FROM gayatri589/open-jdk 
  
WORKDIR /app

# Copy the application JAR file
COPY target/directoryser-0.0.1-SNAPSHOT.jar /app/directory-service.jar

# Start the application
CMD ["java", "-jar","directory-service.jar"]
