FROM gayatri589/open-jdk

WORKDIR /app     
  
# Copy the application JAR file
COPY target/api-gateway-hospital-0.0.1-SNAPSHOT.jar /app/api-gateway.jar
 
# Start the application 
CMD ["java", "-jar","api-gateway.jar"]
