# Use a base image with the required runtime environment
# Use a base image with JDK 
FROM gayatri589/open-jdk  
 
WORKDIR /app     
 
# Copy the application JAR file
COPY target/appointment_service-0.0.1-SNAPSHOT.jar /app/appointment-service.jar

# Start the application
CMD ["java", "-jar","appointment-service.jar"]
