# Use a base image with the required runtime environment
# Use a base image with JDK 
FROM gayatri589/open-jdk 

WORKDIR /app    
 
ARG imageName=hospital_management_project-latest  
ENV IMAGE_NAME=${imageName} 

COPY target/${IMAGE_NAME}.jar ${IMAGE_NAME}.jar

ENTRYPOINT ["sh", "-c", "java -jar /app/${IMAGE_NAME}.jar"]
