FROM gayatri589/open-jdk

# Set the working directory inside the container 
WORKDIR /app

# Copy the application JAR file from the target directory
COPY target/*.jar /app/case-service.jar

# Start the application
CMD ["java", "-jar", "/app/case-service.jar"]
