name: Build Appointment service image

on: 
  push:
    paths:
      - hospital-management/appointment-service/**

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Perform google formatter check
        run: |
          cd hospital-management/appointment-service
          mvn com.spotify.fmt:fmt-maven-plugin:check

      - name: License finder
        run: |
          cd hospital-management/appointment-service
          docker pull gayatri589/license-finder
          docker run -v "$(pwd):/scan" gayatri589/license-finder
        continue-on-error: true

      - name: GitLeaks Scan
        uses: zricethezav/gitleaks-action@v1.3.0
        with:
          args: --path=cd hospital-management/appointment-service

      - name: OSS scan
        run: |
          cd hospital-management/appointment-service
          mvn ossindex:audit
        continue-on-error: true

      - name: OWASP Scan
        if: false
        run: |
          cd hospital-management/appointment-service
          mvn org.owasp:dependency-check-maven:check

      - name: Build code and create docker image
        run: |
          cd hospital-management/appointment-service
          mvn clean install docker:build -Dimage.registry=${{ secrets.DOCKER_REGISTRY_USER }} -Dimage.tag=$GITHUB_REF_NAME

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASS }}

      - name: Push Docker Image
        run: 
          docker push ${{secrets.DOCKER_REGISTRY_USER}}/appointment_service:$GITHUB_REF_NAME

