name: Build Case Service

on:
  push:
    paths:
      - hospital-management/case-service/**

jobs:
  build-and-push-case-service:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Perform google formatter check
        run: mvn com.spotify.fmt:fmt-maven-plugin:check
        working-directory: hospital-management/case-service


      - name: GitLeaks Scan
        uses: zricethezav/gitleaks-action@v1.3.0

      - name: OSS Scan
        run: mvn ossindex:audit
        continue-on-error: true

      - name: OWASP Scan
        if: false
        run: mvn org.owasp:dependency-check-maven:check

      - name: License finder
        run: |
          cd hospital-management/appointment-service
          docker pull gayatri589/license-finder
          docker run -v "$(pwd):/scan" gayatri589/license-finder
        continue-on-error: true

      - name: Build code and create docker image
        run: |
          cd hospital-management/case-service-service
          mvn clean install docker:build -Dimage.registry=${{ secrets.DOCKER_REGISTRY_USER }} -Dimage.tag=$GITHUB_REF_NAME
        
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASS }}

      - name: Push Docker Image
        run: 
          docker push ${{secrets.DOCKER_REGISTRY_USER}}/case_service:$GITHUB_REF_NAME
 
         
         
