name: CI for Hospital Management Project

on:
  push:
    paths:
      - 'hospital-management/**'

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java Environment
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Validate Project Structure
        run: ls -R
        working-directory: hospital-management

      - name: Show Makefile
        run: cat hospital-management/Makefile

      - name: Run Status
        working-directory: hospital-management
        run: make status

      - name: Pull Latest Changes
        working-directory: hospital-management
        run: make pull

      - name: Stash Changes
        working-directory: hospital-management
        run: make stash

      - name: Build Library Project
        working-directory: hospital-management
        run: make build_lib

      - name: Build Services
        working-directory: hospital-management
        run: make build_services

      - name: Build Docker Images
        working-directory: hospital-management
        run: make build_images

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PAT }}

      - name: Push Docker Images
        working-directory: hospital-management
        run: make push_images
