name: Build and Deploy hospital-management using makefile

on:
  push:
    paths:
      - hospital-management/**

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Clone repositories
        run: make clone

      - name: Check Git status
        run: make status

      - name: Pull latest changes
        run: make pull

      - name: Stash local changes
        run: make stash

      - name: Build library project
        run: make build_lib

      - name: Build services
        run: make build_services

      - name: Build Docker images
        run: make build_images

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Push Docker images to Docker Hub
        run: make push_images
