name: Build Hospital Console project

on:
  push: 
    paths:
      - hospital-management/**
 
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Perform google formatter check
        run: |
          cd hospital-management/hospital-console-project
          mvn com.spotify.fmt:fmt-maven-plugin:check

      - name: GitLeaks Scan
        run: |
          cd hospital-management/hospital-console-project
          docker pull gayatri589/gitleaks
          docker run -v "$(pwd):/scan" gayatri589/gitleaks

      - name: OSS scan
        run: |
          cd hospital-management/hospital-console-project
          mvn ossindex:audit

      - name: OWASP Scan
        if: false
        run: |
          cd hospital-management/hospital-console-project
          mvn org.owasp:dependency-check-maven:check

      - name: License finder
        run: |
          cd hospital-management/hospital-console-project
          docker pull gayatri589/license-finder
          docker run -v "$(pwd):/scan" gayatri589/license-finder
        continue-on-error: true
