name: Build Patient Service image

on:
  push: 
    paths:
      - hospital-management/** 

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Perform google formatter check
        run: |
          cd hospital-management/patient-service
          mvn com.spotify.fmt:fmt-maven-plugin:check

      - name: GitLeaks Scan
        uses: zricethezav/gitleaks-action@v1.3.0
        with:
          args: --path=cd hospital-management/patient-service

      - name: OSS scan
        run: |
          cd hospital-management/patient-service
          mvn ossindex:audit

      - name: OWASP Scan
        if: false
        run: |
          cd hospital-management/patient-service
          mvn org.owasp:dependency-check-maven:check

      - name: Build code and create docker image
        run: |
          cd hospital-management/patient-service
          mvn clean install docker:build _Dimage.registry= ${{ secrets.DOCKER_REGISTRY_USER }} -Dimage.tag=$GITHUB_REF_NAME

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASS }}

      - name: Push Docker Image for patient-service
        run: 
          docker push ${{secrets.DOCKER_REGISTRY_USER}}/patient-service:$GITHUB_REF_NAME
